LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional


LOCAL_SRC_FILES := $(call all-java-files-under, src)

LOCAL_PACKAGE_NAME := UMATV

LOCAL_STATIC_JAVA_LIBRARIES := Hitv

LOCAL_CERTIFICATE := platform

LOCAL_OVERRIDES_PACKAGES := platform

LOCAL_PROGUARD_ENABLED := disabled

ifeq ($(TARGET_BRAND),hisilicon)
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_PACKAGE_NAME)
endif

include $(BUILD_PACKAGE)
